name: Deploy OpenSearch CDK Stack

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
  pull_request:
    branches:
      - main  # Trigger deployment on pull request to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy-stack.outputs.domainEndpoint }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        npm install
        npm run build # if you have a build step for TypeScript

    - name: Configure AWS credentials from role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::804295906245:role/role-github # Role to assume
        aws-region: us-east-1  # Change to your AWS region

    - name: Deploy CDK Stack
      id: deploy-stack
      run: |
        npx cdk deploy --require-approval never

    - name: Output OpenSearch Domain Endpoint
      run: |
        echo "OpenSearch Domain Endpoint: ${{ steps.deploy-stack.outputs.domainEndpoint }}"
